services:
  mongodb:
    image: mongo
    container_name: demo-mongo
    ports:
      - 27017:27017
    volumes:
      - mongo:/data
    environment:
      - MONGO_INITDB_ROOT_USERNAME=testuser
      - MONGO_INITDB_ROOT_PASSWORD=testpw

  mongo-express:
    image: mongo-express
    container_name: demo-mongo-express
    ports:
      - 8081:8081
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=testuser
      - ME_CONFIG_MONGODB_ADMINPASSWORD=testpw
      - ME_CONFIG_MONGODB_SERVER=mongodb

volumes:
  mongo: {}